// Automatically generated by ./configure 
#ifndef _CONFIG_H_
#define _CONFIG_H_
// distro
#define SOLIB_EXT ".so"
#define ARCH "i786"
#define CPU "generic"
#define WITHOUT_OPTIMIZATION 0
#define ENABLE_SSL 1
#define ENABLE_GSSAPI 1
#define ENABLE_DEVEL 0
#define ENABLE_VALGRIND 0
#define ENABLE_REFCNT_DEBUG 0
#define ENABLE_SHAREDPTR_DEBUG 0
#define ENABLE_LZ4_EXT 1
#define ENABLE_LZ4_EXT 1
#define MKL_APP_NAME "librdkafka"
#define MKL_APP_DESC_ONELINE "The Apache Kafka C/C++ library"
// gcc
#define WITH_GCC 1
// gxx
#define WITH_GXX 1
// install
#define WITH_INSTALL 1
// PIC
#define HAVE_PIC 1
// gnulib
#define WITH_GNULD 1
// parseversion
#define RDKAFKA_VERSION_STR "1.0.0"
// parseversion
#define MKL_APP_VERSION "1.0.0"
// libdl
#define WITH_LIBDL 1
// WITH_PLUGINS
#define WITH_PLUGINS 1
// zlib
#define WITH_ZLIB 1
// libsasl2
#define WITH_SASL_CYRUS 1
// WITH_HDRHISTOGRAM
#define WITH_HDRHISTOGRAM 1
// WITH_SNAPPY
#define WITH_SNAPPY 1
// WITH_SOCKEM
#define WITH_SOCKEM 1
// regex
#define HAVE_REGEX 1
// BUILT_WITH
#define BUILT_WITH "GCC GXX INSTALL GNULD LIBDL PLUGINS ZLIB SASL_CYRUS HDRHISTOGRAM SNAPPY SOCKEM"
#endif /* _CONFIG_H_ */
